### PR TITLE
stats - do power calculation for the t-test #6

### PR DESCRIPTION
**Pull request by ang2887**
I did not know what was the best way to submit the code, so I decided to submit two versions: 
1. Non-modularised, which is commented out. 
2. Modularised

### CODE REVIEW

**Comment by ang2887** [comment]
Please, Arad, let me know if there are any issues with the code and what could be done better.

**Comment by a-arad** [comment]
@ang2887 reviewing

**Comment by ang2887** [comment]
Thanks )

**Comment by a-arad** [comment]
hey -- nice job! I made a slight adjustment then merged. instead of having the power calculation in the notebook -- i isolated it to a script.

**Comment by ang2887** [comment]
Thank you!   
  
Next time I’ll try to do this by myself.   
  
  
  
  
  
  
  

  
  
>

**Pull request merged**
