### PR TITLE
# 7 EDA -  relationship between sum_gameroungs, retention_1, retention_7

### PR DESCRIPTION
**Pull request by ang2887**
# 7 EDA - explore the relationship between the different outcome variables

### CODE REVIEW

**Comment by ang2887** [comment]
Hi Arad, I would be happy to receive your suggestions for further improvement!

**Comment by ang2887** [comment]
I realised that resolving merge conflicts in rct.ipynb resulted in almost all of my code being wiped out. Nevertheless, the rct.py script I created should contain all the code I've written 😅

**Comment by a-arad** [comment]
can you handle merge conflicts by refetching the repo, putting work in an independent file, then submitting another PR?

**Comment by ang2887** [comment]
will do!

**Comment by ang2887** [comment]
Hi Arad,
I saw you merged my PR - thanks for that! Just wanted to let you know I’m still working on it. I’ve cleaned up the mess from July, reorganised the files, and found a few ways to improve the code. 
I’m almost done and was wondering if would it be alright to finish up the issue with these updates?
Lena

**Comment by ang2887** [comment]
I meant that I was still working on this issue before the merge. I’ve already synced rct.ipynb with your upstream, cleaned up rct.py and renamed it to eda_relationship.py, set up a virtual environment, and removed the auto-generated notebooks.code-workspace file from VS Code. I also noticed other ways I could improve the code. So, I’d like to finish what I started and present a better version of my work :)

**Pull request merged**
